Skip to content
Navigation Menu
Milad-heydarloo
/
my_loc

Type / to search
Code
Issues
Pull requests
Actions
Projects
Security
Insights
Settings
ğŸ‰ Android Build
ğŸ‰ Android Build #7
Jobs
Run details
ğŸ‰ Android Build
failed now in 3m 38s
Search logs
1s
1s
32s
9s
2m 53s
0s
Run ls -R build/app/outputs/apk/
build/app/outputs/apk/:
release
build/app/outputs/apk/release:
app-arm64-v8a-release.apk
app-armeabi-v7a-release.apk
app-x86_64-release.apk
output-metadata.json
0s
Run mkdir -p release
0s
Run mv build/app/outputs/apk/release/app-arm64-v8a-release.apk release/app-arm64-v8a-release.apk
0s
Run svenstaro/upload-release-action@v2
  
Error: ENOENT: no such file or directory, stat 'release/*.apk'
0s
Post job cleanup.
0s
Post job cleanup.
/usr/bin/git version
git version 2.46.0
Temporarily overriding HOME='/home/runner/work/_temp/1f218433-ccfc-44ad-b435-67632aa972d7' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/my_loc/my_loc
/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
1s
Ø­Ø°Ù Ú©Ù† Ø®Ø±ÙˆØ¬ÛŒ Ø¨Ú¯ÛŒØ±ÛŒÙ…
